/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel struct for ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel
type ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel struct {
	Address ShipBobOrdersPresentationViewModelsEstimationAddressViewModel `json:"address"`
	// Products to be included in the order. Each product must include one of reference_id or id
	Products []ShipBobOrdersPresentationModelsEstimateProductInfoModel `json:"products"`
	// Array of strings specifying shipping methods for which to fetch estimates.\\r\\n\\r\\nIf this field is omitted we will return estimates for all shipping methods defined in ShipBob
	ShippingMethods *[]string `json:"shipping_methods,omitempty"`
}

// NewShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel instantiates a new ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel(address ShipBobOrdersPresentationViewModelsEstimationAddressViewModel, products []ShipBobOrdersPresentationModelsEstimateProductInfoModel, ) *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel {
	this := ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel{}
	this.Address = address
	this.Products = products
	return &this
}

// NewShipBobOrdersPresentationModelsEstimateFulfillmentRequestModelWithDefaults instantiates a new ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipBobOrdersPresentationModelsEstimateFulfillmentRequestModelWithDefaults() *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel {
	this := ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel{}
	return &this
}

// GetAddress returns the Address field value
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetAddress() ShipBobOrdersPresentationViewModelsEstimationAddressViewModel {
	if o == nil  {
		var ret ShipBobOrdersPresentationViewModelsEstimationAddressViewModel
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetAddressOk() (*ShipBobOrdersPresentationViewModelsEstimationAddressViewModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) SetAddress(v ShipBobOrdersPresentationViewModelsEstimationAddressViewModel) {
	o.Address = v
}

// GetProducts returns the Products field value
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetProducts() []ShipBobOrdersPresentationModelsEstimateProductInfoModel {
	if o == nil  {
		var ret []ShipBobOrdersPresentationModelsEstimateProductInfoModel
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetProductsOk() (*[]ShipBobOrdersPresentationModelsEstimateProductInfoModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Products, true
}

// SetProducts sets field value
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) SetProducts(v []ShipBobOrdersPresentationModelsEstimateProductInfoModel) {
	o.Products = v
}

// GetShippingMethods returns the ShippingMethods field value if set, zero value otherwise.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetShippingMethods() []string {
	if o == nil || o.ShippingMethods == nil {
		var ret []string
		return ret
	}
	return *o.ShippingMethods
}

// GetShippingMethodsOk returns a tuple with the ShippingMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) GetShippingMethodsOk() (*[]string, bool) {
	if o == nil || o.ShippingMethods == nil {
		return nil, false
	}
	return o.ShippingMethods, true
}

// HasShippingMethods returns a boolean if a field has been set.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) HasShippingMethods() bool {
	if o != nil && o.ShippingMethods != nil {
		return true
	}

	return false
}

// SetShippingMethods gets a reference to the given []string and assigns it to the ShippingMethods field.
func (o *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) SetShippingMethods(v []string) {
	o.ShippingMethods = &v
}

func (o ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["products"] = o.Products
	}
	if o.ShippingMethods != nil {
		toSerialize["shipping_methods"] = o.ShippingMethods
	}
	return json.Marshal(toSerialize)
}

type NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel struct {
	value *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel
	isSet bool
}

func (v NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) Get() *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel {
	return v.value
}

func (v *NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) Set(val *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel(val *ShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) *NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel {
	return &NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel{value: val, isSet: true}
}

func (v NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipBobOrdersPresentationModelsEstimateFulfillmentRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


