/*
ShipBob Developer API

ShipBob Developer API Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// checks if the Inventory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Inventory{}

// Inventory Information about an inventory item
type Inventory struct {
	Dimensions *Dimension `json:"dimensions,omitempty"`
	// Fulfillable quantity of this inventory item broken down by fulfillment center location
	FulfillableQuantityByFulfillmentCenter []InventoryFulfillmentCenterQuantity `json:"fulfillableQuantityByFulfillmentCenter,omitempty"`
	// Fulfillable quantity of this inventory item broken down by lot
	FulfillableQuantityByLot []InventoryLotQuantity `json:"fulfillableQuantityByLot,omitempty"`
	// Unique id of the inventory item
	InventoryId *int32 `json:"inventoryId,omitempty"`
	// Whether the inventory is active or not
	IsActive *bool `json:"isActive,omitempty"`
	// True if the inventory item is marked as case pick
	IsCasePick *bool `json:"isCasePick,omitempty"`
	// True if the inventory item is marked as a digital item
	IsDigital *bool `json:"isDigital,omitempty"`
	// True if this inventory item is organized into lots
	IsLot *bool `json:"isLot,omitempty"`
	// Name of the inventory item
	Name               NullableString      `json:"name,omitempty"`
	PackagingAttribute *PackagingAttribute `json:"packagingAttribute,omitempty"`
	// Total quantity in unreceived receiving orders for this inventory item
	TotalAwaitingQuantity *int32 `json:"totalAwaitingQuantity,omitempty"`
	// The amount of the item you need to send to ShipBob to fulfill all exception orders containing  the item. This is the exception_quantity less the fulfillable_quantity of the item.
	TotalBackorderedQuantity *int32 `json:"totalBackorderedQuantity,omitempty"`
	// Total committed quantity of this inventory item
	TotalCommitedQuantity *int32 `json:"totalCommitedQuantity,omitempty"`
	// The total quantity of all items that are contained within orders that are in exception/out of stock status. Out of stock orders have not been processed and therefore do not have lot or fulfillment centers assigned.
	TotalExceptionQuantity *int32 `json:"totalExceptionQuantity,omitempty"`
	// Total fulfillable quantity of this inventory item
	TotalFulfillableQuantity *int32 `json:"totalFulfillableQuantity,omitempty"`
	// The total quantity of all items that are in the process of internal transit  between ShipBob fulfillment centers. These items are not pickable or fulfillable until they have been received and moved to the \"On Hand\" quantity of the destination FC. Internal transit quantities for each FC represent the incoming transfer stock for that specific location.
	TotalInternalTransferQuantity *int32 `json:"totalInternalTransferQuantity,omitempty"`
	// Total onhand quantity of this inventory item
	TotalOnHandQuantity *int32 `json:"totalOnHandQuantity,omitempty"`
	// Total quantity that can be sold without overselling the inventory item. This is calculated by subtracting the total exception quantity from the fulfillable quantity.
	TotalSellableQuantity *int32 `json:"totalSellableQuantity,omitempty"`
}

// NewInventory instantiates a new Inventory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventory() *Inventory {
	this := Inventory{}
	return &this
}

// NewInventoryWithDefaults instantiates a new Inventory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryWithDefaults() *Inventory {
	this := Inventory{}
	return &this
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *Inventory) GetDimensions() Dimension {
	if o == nil || IsNil(o.Dimensions) {
		var ret Dimension
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetDimensionsOk() (*Dimension, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *Inventory) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given Dimension and assigns it to the Dimensions field.
func (o *Inventory) SetDimensions(v Dimension) {
	o.Dimensions = &v
}

// GetFulfillableQuantityByFulfillmentCenter returns the FulfillableQuantityByFulfillmentCenter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Inventory) GetFulfillableQuantityByFulfillmentCenter() []InventoryFulfillmentCenterQuantity {
	if o == nil {
		var ret []InventoryFulfillmentCenterQuantity
		return ret
	}
	return o.FulfillableQuantityByFulfillmentCenter
}

// GetFulfillableQuantityByFulfillmentCenterOk returns a tuple with the FulfillableQuantityByFulfillmentCenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Inventory) GetFulfillableQuantityByFulfillmentCenterOk() ([]InventoryFulfillmentCenterQuantity, bool) {
	if o == nil || IsNil(o.FulfillableQuantityByFulfillmentCenter) {
		return nil, false
	}
	return o.FulfillableQuantityByFulfillmentCenter, true
}

// HasFulfillableQuantityByFulfillmentCenter returns a boolean if a field has been set.
func (o *Inventory) HasFulfillableQuantityByFulfillmentCenter() bool {
	if o != nil && IsNil(o.FulfillableQuantityByFulfillmentCenter) {
		return true
	}

	return false
}

// SetFulfillableQuantityByFulfillmentCenter gets a reference to the given []InventoryFulfillmentCenterQuantity and assigns it to the FulfillableQuantityByFulfillmentCenter field.
func (o *Inventory) SetFulfillableQuantityByFulfillmentCenter(v []InventoryFulfillmentCenterQuantity) {
	o.FulfillableQuantityByFulfillmentCenter = v
}

// GetFulfillableQuantityByLot returns the FulfillableQuantityByLot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Inventory) GetFulfillableQuantityByLot() []InventoryLotQuantity {
	if o == nil {
		var ret []InventoryLotQuantity
		return ret
	}
	return o.FulfillableQuantityByLot
}

// GetFulfillableQuantityByLotOk returns a tuple with the FulfillableQuantityByLot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Inventory) GetFulfillableQuantityByLotOk() ([]InventoryLotQuantity, bool) {
	if o == nil || IsNil(o.FulfillableQuantityByLot) {
		return nil, false
	}
	return o.FulfillableQuantityByLot, true
}

// HasFulfillableQuantityByLot returns a boolean if a field has been set.
func (o *Inventory) HasFulfillableQuantityByLot() bool {
	if o != nil && IsNil(o.FulfillableQuantityByLot) {
		return true
	}

	return false
}

// SetFulfillableQuantityByLot gets a reference to the given []InventoryLotQuantity and assigns it to the FulfillableQuantityByLot field.
func (o *Inventory) SetFulfillableQuantityByLot(v []InventoryLotQuantity) {
	o.FulfillableQuantityByLot = v
}

// GetInventoryId returns the InventoryId field value if set, zero value otherwise.
func (o *Inventory) GetInventoryId() int32 {
	if o == nil || IsNil(o.InventoryId) {
		var ret int32
		return ret
	}
	return *o.InventoryId
}

// GetInventoryIdOk returns a tuple with the InventoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetInventoryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.InventoryId) {
		return nil, false
	}
	return o.InventoryId, true
}

// HasInventoryId returns a boolean if a field has been set.
func (o *Inventory) HasInventoryId() bool {
	if o != nil && !IsNil(o.InventoryId) {
		return true
	}

	return false
}

// SetInventoryId gets a reference to the given int32 and assigns it to the InventoryId field.
func (o *Inventory) SetInventoryId(v int32) {
	o.InventoryId = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *Inventory) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *Inventory) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *Inventory) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetIsCasePick returns the IsCasePick field value if set, zero value otherwise.
func (o *Inventory) GetIsCasePick() bool {
	if o == nil || IsNil(o.IsCasePick) {
		var ret bool
		return ret
	}
	return *o.IsCasePick
}

// GetIsCasePickOk returns a tuple with the IsCasePick field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetIsCasePickOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCasePick) {
		return nil, false
	}
	return o.IsCasePick, true
}

// HasIsCasePick returns a boolean if a field has been set.
func (o *Inventory) HasIsCasePick() bool {
	if o != nil && !IsNil(o.IsCasePick) {
		return true
	}

	return false
}

// SetIsCasePick gets a reference to the given bool and assigns it to the IsCasePick field.
func (o *Inventory) SetIsCasePick(v bool) {
	o.IsCasePick = &v
}

// GetIsDigital returns the IsDigital field value if set, zero value otherwise.
func (o *Inventory) GetIsDigital() bool {
	if o == nil || IsNil(o.IsDigital) {
		var ret bool
		return ret
	}
	return *o.IsDigital
}

// GetIsDigitalOk returns a tuple with the IsDigital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetIsDigitalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDigital) {
		return nil, false
	}
	return o.IsDigital, true
}

// HasIsDigital returns a boolean if a field has been set.
func (o *Inventory) HasIsDigital() bool {
	if o != nil && !IsNil(o.IsDigital) {
		return true
	}

	return false
}

// SetIsDigital gets a reference to the given bool and assigns it to the IsDigital field.
func (o *Inventory) SetIsDigital(v bool) {
	o.IsDigital = &v
}

// GetIsLot returns the IsLot field value if set, zero value otherwise.
func (o *Inventory) GetIsLot() bool {
	if o == nil || IsNil(o.IsLot) {
		var ret bool
		return ret
	}
	return *o.IsLot
}

// GetIsLotOk returns a tuple with the IsLot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetIsLotOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLot) {
		return nil, false
	}
	return o.IsLot, true
}

// HasIsLot returns a boolean if a field has been set.
func (o *Inventory) HasIsLot() bool {
	if o != nil && !IsNil(o.IsLot) {
		return true
	}

	return false
}

// SetIsLot gets a reference to the given bool and assigns it to the IsLot field.
func (o *Inventory) SetIsLot(v bool) {
	o.IsLot = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Inventory) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Inventory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *Inventory) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *Inventory) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *Inventory) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *Inventory) UnsetName() {
	o.Name.Unset()
}

// GetPackagingAttribute returns the PackagingAttribute field value if set, zero value otherwise.
func (o *Inventory) GetPackagingAttribute() PackagingAttribute {
	if o == nil || IsNil(o.PackagingAttribute) {
		var ret PackagingAttribute
		return ret
	}
	return *o.PackagingAttribute
}

// GetPackagingAttributeOk returns a tuple with the PackagingAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetPackagingAttributeOk() (*PackagingAttribute, bool) {
	if o == nil || IsNil(o.PackagingAttribute) {
		return nil, false
	}
	return o.PackagingAttribute, true
}

// HasPackagingAttribute returns a boolean if a field has been set.
func (o *Inventory) HasPackagingAttribute() bool {
	if o != nil && !IsNil(o.PackagingAttribute) {
		return true
	}

	return false
}

// SetPackagingAttribute gets a reference to the given PackagingAttribute and assigns it to the PackagingAttribute field.
func (o *Inventory) SetPackagingAttribute(v PackagingAttribute) {
	o.PackagingAttribute = &v
}

// GetTotalAwaitingQuantity returns the TotalAwaitingQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalAwaitingQuantity() int32 {
	if o == nil || IsNil(o.TotalAwaitingQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalAwaitingQuantity
}

// GetTotalAwaitingQuantityOk returns a tuple with the TotalAwaitingQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalAwaitingQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalAwaitingQuantity) {
		return nil, false
	}
	return o.TotalAwaitingQuantity, true
}

// HasTotalAwaitingQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalAwaitingQuantity() bool {
	if o != nil && !IsNil(o.TotalAwaitingQuantity) {
		return true
	}

	return false
}

// SetTotalAwaitingQuantity gets a reference to the given int32 and assigns it to the TotalAwaitingQuantity field.
func (o *Inventory) SetTotalAwaitingQuantity(v int32) {
	o.TotalAwaitingQuantity = &v
}

// GetTotalBackorderedQuantity returns the TotalBackorderedQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalBackorderedQuantity() int32 {
	if o == nil || IsNil(o.TotalBackorderedQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalBackorderedQuantity
}

// GetTotalBackorderedQuantityOk returns a tuple with the TotalBackorderedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalBackorderedQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalBackorderedQuantity) {
		return nil, false
	}
	return o.TotalBackorderedQuantity, true
}

// HasTotalBackorderedQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalBackorderedQuantity() bool {
	if o != nil && !IsNil(o.TotalBackorderedQuantity) {
		return true
	}

	return false
}

// SetTotalBackorderedQuantity gets a reference to the given int32 and assigns it to the TotalBackorderedQuantity field.
func (o *Inventory) SetTotalBackorderedQuantity(v int32) {
	o.TotalBackorderedQuantity = &v
}

// GetTotalCommitedQuantity returns the TotalCommitedQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalCommitedQuantity() int32 {
	if o == nil || IsNil(o.TotalCommitedQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalCommitedQuantity
}

// GetTotalCommitedQuantityOk returns a tuple with the TotalCommitedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalCommitedQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCommitedQuantity) {
		return nil, false
	}
	return o.TotalCommitedQuantity, true
}

// HasTotalCommitedQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalCommitedQuantity() bool {
	if o != nil && !IsNil(o.TotalCommitedQuantity) {
		return true
	}

	return false
}

// SetTotalCommitedQuantity gets a reference to the given int32 and assigns it to the TotalCommitedQuantity field.
func (o *Inventory) SetTotalCommitedQuantity(v int32) {
	o.TotalCommitedQuantity = &v
}

// GetTotalExceptionQuantity returns the TotalExceptionQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalExceptionQuantity() int32 {
	if o == nil || IsNil(o.TotalExceptionQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalExceptionQuantity
}

// GetTotalExceptionQuantityOk returns a tuple with the TotalExceptionQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalExceptionQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalExceptionQuantity) {
		return nil, false
	}
	return o.TotalExceptionQuantity, true
}

// HasTotalExceptionQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalExceptionQuantity() bool {
	if o != nil && !IsNil(o.TotalExceptionQuantity) {
		return true
	}

	return false
}

// SetTotalExceptionQuantity gets a reference to the given int32 and assigns it to the TotalExceptionQuantity field.
func (o *Inventory) SetTotalExceptionQuantity(v int32) {
	o.TotalExceptionQuantity = &v
}

// GetTotalFulfillableQuantity returns the TotalFulfillableQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalFulfillableQuantity() int32 {
	if o == nil || IsNil(o.TotalFulfillableQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalFulfillableQuantity
}

// GetTotalFulfillableQuantityOk returns a tuple with the TotalFulfillableQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalFulfillableQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalFulfillableQuantity) {
		return nil, false
	}
	return o.TotalFulfillableQuantity, true
}

// HasTotalFulfillableQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalFulfillableQuantity() bool {
	if o != nil && !IsNil(o.TotalFulfillableQuantity) {
		return true
	}

	return false
}

// SetTotalFulfillableQuantity gets a reference to the given int32 and assigns it to the TotalFulfillableQuantity field.
func (o *Inventory) SetTotalFulfillableQuantity(v int32) {
	o.TotalFulfillableQuantity = &v
}

// GetTotalInternalTransferQuantity returns the TotalInternalTransferQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalInternalTransferQuantity() int32 {
	if o == nil || IsNil(o.TotalInternalTransferQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalInternalTransferQuantity
}

// GetTotalInternalTransferQuantityOk returns a tuple with the TotalInternalTransferQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalInternalTransferQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInternalTransferQuantity) {
		return nil, false
	}
	return o.TotalInternalTransferQuantity, true
}

// HasTotalInternalTransferQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalInternalTransferQuantity() bool {
	if o != nil && !IsNil(o.TotalInternalTransferQuantity) {
		return true
	}

	return false
}

// SetTotalInternalTransferQuantity gets a reference to the given int32 and assigns it to the TotalInternalTransferQuantity field.
func (o *Inventory) SetTotalInternalTransferQuantity(v int32) {
	o.TotalInternalTransferQuantity = &v
}

// GetTotalOnHandQuantity returns the TotalOnHandQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalOnHandQuantity() int32 {
	if o == nil || IsNil(o.TotalOnHandQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalOnHandQuantity
}

// GetTotalOnHandQuantityOk returns a tuple with the TotalOnHandQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalOnHandQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalOnHandQuantity) {
		return nil, false
	}
	return o.TotalOnHandQuantity, true
}

// HasTotalOnHandQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalOnHandQuantity() bool {
	if o != nil && !IsNil(o.TotalOnHandQuantity) {
		return true
	}

	return false
}

// SetTotalOnHandQuantity gets a reference to the given int32 and assigns it to the TotalOnHandQuantity field.
func (o *Inventory) SetTotalOnHandQuantity(v int32) {
	o.TotalOnHandQuantity = &v
}

// GetTotalSellableQuantity returns the TotalSellableQuantity field value if set, zero value otherwise.
func (o *Inventory) GetTotalSellableQuantity() int32 {
	if o == nil || IsNil(o.TotalSellableQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalSellableQuantity
}

// GetTotalSellableQuantityOk returns a tuple with the TotalSellableQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inventory) GetTotalSellableQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSellableQuantity) {
		return nil, false
	}
	return o.TotalSellableQuantity, true
}

// HasTotalSellableQuantity returns a boolean if a field has been set.
func (o *Inventory) HasTotalSellableQuantity() bool {
	if o != nil && !IsNil(o.TotalSellableQuantity) {
		return true
	}

	return false
}

// SetTotalSellableQuantity gets a reference to the given int32 and assigns it to the TotalSellableQuantity field.
func (o *Inventory) SetTotalSellableQuantity(v int32) {
	o.TotalSellableQuantity = &v
}

func (o Inventory) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Inventory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if o.FulfillableQuantityByFulfillmentCenter != nil {
		toSerialize["fulfillableQuantityByFulfillmentCenter"] = o.FulfillableQuantityByFulfillmentCenter
	}
	if o.FulfillableQuantityByLot != nil {
		toSerialize["fulfillableQuantityByLot"] = o.FulfillableQuantityByLot
	}
	if !IsNil(o.InventoryId) {
		toSerialize["inventoryId"] = o.InventoryId
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	if !IsNil(o.IsCasePick) {
		toSerialize["isCasePick"] = o.IsCasePick
	}
	if !IsNil(o.IsDigital) {
		toSerialize["isDigital"] = o.IsDigital
	}
	if !IsNil(o.IsLot) {
		toSerialize["isLot"] = o.IsLot
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.PackagingAttribute) {
		toSerialize["packagingAttribute"] = o.PackagingAttribute
	}
	if !IsNil(o.TotalAwaitingQuantity) {
		toSerialize["totalAwaitingQuantity"] = o.TotalAwaitingQuantity
	}
	if !IsNil(o.TotalBackorderedQuantity) {
		toSerialize["totalBackorderedQuantity"] = o.TotalBackorderedQuantity
	}
	if !IsNil(o.TotalCommitedQuantity) {
		toSerialize["totalCommitedQuantity"] = o.TotalCommitedQuantity
	}
	if !IsNil(o.TotalExceptionQuantity) {
		toSerialize["totalExceptionQuantity"] = o.TotalExceptionQuantity
	}
	if !IsNil(o.TotalFulfillableQuantity) {
		toSerialize["totalFulfillableQuantity"] = o.TotalFulfillableQuantity
	}
	if !IsNil(o.TotalInternalTransferQuantity) {
		toSerialize["totalInternalTransferQuantity"] = o.TotalInternalTransferQuantity
	}
	if !IsNil(o.TotalOnHandQuantity) {
		toSerialize["totalOnHandQuantity"] = o.TotalOnHandQuantity
	}
	if !IsNil(o.TotalSellableQuantity) {
		toSerialize["totalSellableQuantity"] = o.TotalSellableQuantity
	}
	return toSerialize, nil
}

type NullableInventory struct {
	value *Inventory
	isSet bool
}

func (v NullableInventory) Get() *Inventory {
	return v.value
}

func (v *NullableInventory) Set(val *Inventory) {
	v.value = val
	v.isSet = true
}

func (v NullableInventory) IsSet() bool {
	return v.isSet
}

func (v *NullableInventory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventory(val *Inventory) *NullableInventory {
	return &NullableInventory{value: val, isSet: true}
}

func (v NullableInventory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
