/*
ShipBob Developer API

ShipBob Developer API Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// checks if the AssignOrderToFulfillmentCenter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignOrderToFulfillmentCenter{}

// AssignOrderToFulfillmentCenter Model containing information that assigns a receiving order to a fulfillment center. If the fulfillment center provided is in a receiving hub region, then the response will be the receiving hub location.
type AssignOrderToFulfillmentCenter struct {
	// ID of the fulfillment center to assign this receiving order to
	Id int32 `json:"id"`
}

// NewAssignOrderToFulfillmentCenter instantiates a new AssignOrderToFulfillmentCenter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignOrderToFulfillmentCenter(id int32) *AssignOrderToFulfillmentCenter {
	this := AssignOrderToFulfillmentCenter{}
	this.Id = id
	return &this
}

// NewAssignOrderToFulfillmentCenterWithDefaults instantiates a new AssignOrderToFulfillmentCenter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignOrderToFulfillmentCenterWithDefaults() *AssignOrderToFulfillmentCenter {
	this := AssignOrderToFulfillmentCenter{}
	return &this
}

// GetId returns the Id field value
func (o *AssignOrderToFulfillmentCenter) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AssignOrderToFulfillmentCenter) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AssignOrderToFulfillmentCenter) SetId(v int32) {
	o.Id = v
}

func (o AssignOrderToFulfillmentCenter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignOrderToFulfillmentCenter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableAssignOrderToFulfillmentCenter struct {
	value *AssignOrderToFulfillmentCenter
	isSet bool
}

func (v NullableAssignOrderToFulfillmentCenter) Get() *AssignOrderToFulfillmentCenter {
	return v.value
}

func (v *NullableAssignOrderToFulfillmentCenter) Set(val *AssignOrderToFulfillmentCenter) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignOrderToFulfillmentCenter) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignOrderToFulfillmentCenter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignOrderToFulfillmentCenter(val *AssignOrderToFulfillmentCenter) *NullableAssignOrderToFulfillmentCenter {
	return &NullableAssignOrderToFulfillmentCenter{value: val, isSet: true}
}

func (v NullableAssignOrderToFulfillmentCenter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignOrderToFulfillmentCenter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
