/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"time"
)

// OrdersShipmentViewModel Information about a shipment
type OrdersShipmentViewModel struct {
	// The datetime of ShipBobâs completion of the fulfillment operation as promised. \\r\\nCurrently, this means the shipment has been picked, packed, and label has been printed.
	ActualFulfillmentDate NullableTime `json:"actual_fulfillment_date,omitempty"`
	// Date this shipment was created
	CreatedDate *time.Time `json:"created_date,omitempty"`
	// The datetime of ShipBobâs commitment for completing \\r\\nthe shipment and handing to the carrier for delivery.
	EstimatedFulfillmentDate NullableTime `json:"estimated_fulfillment_date,omitempty"`
	// Status of ShipBobâs completion of the fulfillment operation.
	EstimatedFulfillmentDateStatus *string `json:"estimated_fulfillment_date_status,omitempty"`
	// Unique id of the shipment
	Id *int32 `json:"id,omitempty"`
	// Monetary amount that this shipment was insured for
	InsuranceValue NullableFloat64 `json:"insurance_value,omitempty"`
	// Monetary amount that was invoiced for this shipment
	InvoiceAmount NullableFloat64 `json:"invoice_amount,omitempty"`
	// Date this shipment was last updated
	LastUpdateAt NullableTime `json:"last_update_at,omitempty"`
	Location *OrdersFulfillmentCenterViewModel `json:"location,omitempty"`
	Measurements *OrdersMeasurementsViewModel `json:"measurements,omitempty"`
	// Id of the order this shipment belongs to
	OrderId *int32 `json:"order_id,omitempty"`
	// Container type for the shipment
	PackageMaterialType *string `json:"package_material_type,omitempty"`
	// Information about the products contained in this shipment
	Products *[]OrdersShipmentProductViewModel `json:"products,omitempty"`
	Recipient *OrdersRecipientViewModel `json:"recipient,omitempty"`
	// Client-defined external unique id of the order this shipment belongs to
	ReferenceId *string `json:"reference_id,omitempty"`
	// If a shipment requires signature
	RequireSignature *bool `json:"require_signature,omitempty"`
	// Name of the shipping option used for this shipment
	ShipOption *string `json:"ship_option,omitempty"`
	// The shipment status
	Status *string `json:"status,omitempty"`
	// Additional details about the shipment status
	StatusDetails *[]OrdersStatusDetailViewModel `json:"status_details,omitempty"`
	Tracking *OrdersTrackingViewModel `json:"tracking,omitempty"`
}

// NewOrdersShipmentViewModel instantiates a new OrdersShipmentViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersShipmentViewModel() *OrdersShipmentViewModel {
	this := OrdersShipmentViewModel{}
	return &this
}

// NewOrdersShipmentViewModelWithDefaults instantiates a new OrdersShipmentViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersShipmentViewModelWithDefaults() *OrdersShipmentViewModel {
	this := OrdersShipmentViewModel{}
	return &this
}

// GetActualFulfillmentDate returns the ActualFulfillmentDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersShipmentViewModel) GetActualFulfillmentDate() time.Time {
	if o == nil || o.ActualFulfillmentDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.ActualFulfillmentDate.Get()
}

// GetActualFulfillmentDateOk returns a tuple with the ActualFulfillmentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersShipmentViewModel) GetActualFulfillmentDateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ActualFulfillmentDate.Get(), o.ActualFulfillmentDate.IsSet()
}

// HasActualFulfillmentDate returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasActualFulfillmentDate() bool {
	if o != nil && o.ActualFulfillmentDate.IsSet() {
		return true
	}

	return false
}

// SetActualFulfillmentDate gets a reference to the given NullableTime and assigns it to the ActualFulfillmentDate field.
func (o *OrdersShipmentViewModel) SetActualFulfillmentDate(v time.Time) {
	o.ActualFulfillmentDate.Set(&v)
}
// SetActualFulfillmentDateNil sets the value for ActualFulfillmentDate to be an explicit nil
func (o *OrdersShipmentViewModel) SetActualFulfillmentDateNil() {
	o.ActualFulfillmentDate.Set(nil)
}

// UnsetActualFulfillmentDate ensures that no value is present for ActualFulfillmentDate, not even an explicit nil
func (o *OrdersShipmentViewModel) UnsetActualFulfillmentDate() {
	o.ActualFulfillmentDate.Unset()
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetCreatedDate() time.Time {
	if o == nil || o.CreatedDate == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || o.CreatedDate == nil {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasCreatedDate() bool {
	if o != nil && o.CreatedDate != nil {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *OrdersShipmentViewModel) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetEstimatedFulfillmentDate returns the EstimatedFulfillmentDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersShipmentViewModel) GetEstimatedFulfillmentDate() time.Time {
	if o == nil || o.EstimatedFulfillmentDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.EstimatedFulfillmentDate.Get()
}

// GetEstimatedFulfillmentDateOk returns a tuple with the EstimatedFulfillmentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersShipmentViewModel) GetEstimatedFulfillmentDateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.EstimatedFulfillmentDate.Get(), o.EstimatedFulfillmentDate.IsSet()
}

// HasEstimatedFulfillmentDate returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasEstimatedFulfillmentDate() bool {
	if o != nil && o.EstimatedFulfillmentDate.IsSet() {
		return true
	}

	return false
}

// SetEstimatedFulfillmentDate gets a reference to the given NullableTime and assigns it to the EstimatedFulfillmentDate field.
func (o *OrdersShipmentViewModel) SetEstimatedFulfillmentDate(v time.Time) {
	o.EstimatedFulfillmentDate.Set(&v)
}
// SetEstimatedFulfillmentDateNil sets the value for EstimatedFulfillmentDate to be an explicit nil
func (o *OrdersShipmentViewModel) SetEstimatedFulfillmentDateNil() {
	o.EstimatedFulfillmentDate.Set(nil)
}

// UnsetEstimatedFulfillmentDate ensures that no value is present for EstimatedFulfillmentDate, not even an explicit nil
func (o *OrdersShipmentViewModel) UnsetEstimatedFulfillmentDate() {
	o.EstimatedFulfillmentDate.Unset()
}

// GetEstimatedFulfillmentDateStatus returns the EstimatedFulfillmentDateStatus field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetEstimatedFulfillmentDateStatus() string {
	if o == nil || o.EstimatedFulfillmentDateStatus == nil {
		var ret string
		return ret
	}
	return *o.EstimatedFulfillmentDateStatus
}

// GetEstimatedFulfillmentDateStatusOk returns a tuple with the EstimatedFulfillmentDateStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetEstimatedFulfillmentDateStatusOk() (*string, bool) {
	if o == nil || o.EstimatedFulfillmentDateStatus == nil {
		return nil, false
	}
	return o.EstimatedFulfillmentDateStatus, true
}

// HasEstimatedFulfillmentDateStatus returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasEstimatedFulfillmentDateStatus() bool {
	if o != nil && o.EstimatedFulfillmentDateStatus != nil {
		return true
	}

	return false
}

// SetEstimatedFulfillmentDateStatus gets a reference to the given string and assigns it to the EstimatedFulfillmentDateStatus field.
func (o *OrdersShipmentViewModel) SetEstimatedFulfillmentDateStatus(v string) {
	o.EstimatedFulfillmentDateStatus = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OrdersShipmentViewModel) SetId(v int32) {
	o.Id = &v
}

// GetInsuranceValue returns the InsuranceValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersShipmentViewModel) GetInsuranceValue() float64 {
	if o == nil || o.InsuranceValue.Get() == nil {
		var ret float64
		return ret
	}
	return *o.InsuranceValue.Get()
}

// GetInsuranceValueOk returns a tuple with the InsuranceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersShipmentViewModel) GetInsuranceValueOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InsuranceValue.Get(), o.InsuranceValue.IsSet()
}

// HasInsuranceValue returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasInsuranceValue() bool {
	if o != nil && o.InsuranceValue.IsSet() {
		return true
	}

	return false
}

// SetInsuranceValue gets a reference to the given NullableFloat64 and assigns it to the InsuranceValue field.
func (o *OrdersShipmentViewModel) SetInsuranceValue(v float64) {
	o.InsuranceValue.Set(&v)
}
// SetInsuranceValueNil sets the value for InsuranceValue to be an explicit nil
func (o *OrdersShipmentViewModel) SetInsuranceValueNil() {
	o.InsuranceValue.Set(nil)
}

// UnsetInsuranceValue ensures that no value is present for InsuranceValue, not even an explicit nil
func (o *OrdersShipmentViewModel) UnsetInsuranceValue() {
	o.InsuranceValue.Unset()
}

// GetInvoiceAmount returns the InvoiceAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersShipmentViewModel) GetInvoiceAmount() float64 {
	if o == nil || o.InvoiceAmount.Get() == nil {
		var ret float64
		return ret
	}
	return *o.InvoiceAmount.Get()
}

// GetInvoiceAmountOk returns a tuple with the InvoiceAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersShipmentViewModel) GetInvoiceAmountOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InvoiceAmount.Get(), o.InvoiceAmount.IsSet()
}

// HasInvoiceAmount returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasInvoiceAmount() bool {
	if o != nil && o.InvoiceAmount.IsSet() {
		return true
	}

	return false
}

// SetInvoiceAmount gets a reference to the given NullableFloat64 and assigns it to the InvoiceAmount field.
func (o *OrdersShipmentViewModel) SetInvoiceAmount(v float64) {
	o.InvoiceAmount.Set(&v)
}
// SetInvoiceAmountNil sets the value for InvoiceAmount to be an explicit nil
func (o *OrdersShipmentViewModel) SetInvoiceAmountNil() {
	o.InvoiceAmount.Set(nil)
}

// UnsetInvoiceAmount ensures that no value is present for InvoiceAmount, not even an explicit nil
func (o *OrdersShipmentViewModel) UnsetInvoiceAmount() {
	o.InvoiceAmount.Unset()
}

// GetLastUpdateAt returns the LastUpdateAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersShipmentViewModel) GetLastUpdateAt() time.Time {
	if o == nil || o.LastUpdateAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.LastUpdateAt.Get()
}

// GetLastUpdateAtOk returns a tuple with the LastUpdateAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersShipmentViewModel) GetLastUpdateAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastUpdateAt.Get(), o.LastUpdateAt.IsSet()
}

// HasLastUpdateAt returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasLastUpdateAt() bool {
	if o != nil && o.LastUpdateAt.IsSet() {
		return true
	}

	return false
}

// SetLastUpdateAt gets a reference to the given NullableTime and assigns it to the LastUpdateAt field.
func (o *OrdersShipmentViewModel) SetLastUpdateAt(v time.Time) {
	o.LastUpdateAt.Set(&v)
}
// SetLastUpdateAtNil sets the value for LastUpdateAt to be an explicit nil
func (o *OrdersShipmentViewModel) SetLastUpdateAtNil() {
	o.LastUpdateAt.Set(nil)
}

// UnsetLastUpdateAt ensures that no value is present for LastUpdateAt, not even an explicit nil
func (o *OrdersShipmentViewModel) UnsetLastUpdateAt() {
	o.LastUpdateAt.Unset()
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetLocation() OrdersFulfillmentCenterViewModel {
	if o == nil || o.Location == nil {
		var ret OrdersFulfillmentCenterViewModel
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetLocationOk() (*OrdersFulfillmentCenterViewModel, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given OrdersFulfillmentCenterViewModel and assigns it to the Location field.
func (o *OrdersShipmentViewModel) SetLocation(v OrdersFulfillmentCenterViewModel) {
	o.Location = &v
}

// GetMeasurements returns the Measurements field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetMeasurements() OrdersMeasurementsViewModel {
	if o == nil || o.Measurements == nil {
		var ret OrdersMeasurementsViewModel
		return ret
	}
	return *o.Measurements
}

// GetMeasurementsOk returns a tuple with the Measurements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetMeasurementsOk() (*OrdersMeasurementsViewModel, bool) {
	if o == nil || o.Measurements == nil {
		return nil, false
	}
	return o.Measurements, true
}

// HasMeasurements returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasMeasurements() bool {
	if o != nil && o.Measurements != nil {
		return true
	}

	return false
}

// SetMeasurements gets a reference to the given OrdersMeasurementsViewModel and assigns it to the Measurements field.
func (o *OrdersShipmentViewModel) SetMeasurements(v OrdersMeasurementsViewModel) {
	o.Measurements = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetOrderId() int32 {
	if o == nil || o.OrderId == nil {
		var ret int32
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetOrderIdOk() (*int32, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int32 and assigns it to the OrderId field.
func (o *OrdersShipmentViewModel) SetOrderId(v int32) {
	o.OrderId = &v
}

// GetPackageMaterialType returns the PackageMaterialType field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetPackageMaterialType() string {
	if o == nil || o.PackageMaterialType == nil {
		var ret string
		return ret
	}
	return *o.PackageMaterialType
}

// GetPackageMaterialTypeOk returns a tuple with the PackageMaterialType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetPackageMaterialTypeOk() (*string, bool) {
	if o == nil || o.PackageMaterialType == nil {
		return nil, false
	}
	return o.PackageMaterialType, true
}

// HasPackageMaterialType returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasPackageMaterialType() bool {
	if o != nil && o.PackageMaterialType != nil {
		return true
	}

	return false
}

// SetPackageMaterialType gets a reference to the given string and assigns it to the PackageMaterialType field.
func (o *OrdersShipmentViewModel) SetPackageMaterialType(v string) {
	o.PackageMaterialType = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetProducts() []OrdersShipmentProductViewModel {
	if o == nil || o.Products == nil {
		var ret []OrdersShipmentProductViewModel
		return ret
	}
	return *o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetProductsOk() (*[]OrdersShipmentProductViewModel, bool) {
	if o == nil || o.Products == nil {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasProducts() bool {
	if o != nil && o.Products != nil {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []OrdersShipmentProductViewModel and assigns it to the Products field.
func (o *OrdersShipmentViewModel) SetProducts(v []OrdersShipmentProductViewModel) {
	o.Products = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetRecipient() OrdersRecipientViewModel {
	if o == nil || o.Recipient == nil {
		var ret OrdersRecipientViewModel
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetRecipientOk() (*OrdersRecipientViewModel, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given OrdersRecipientViewModel and assigns it to the Recipient field.
func (o *OrdersShipmentViewModel) SetRecipient(v OrdersRecipientViewModel) {
	o.Recipient = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetReferenceId() string {
	if o == nil || o.ReferenceId == nil {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetReferenceIdOk() (*string, bool) {
	if o == nil || o.ReferenceId == nil {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasReferenceId() bool {
	if o != nil && o.ReferenceId != nil {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *OrdersShipmentViewModel) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetRequireSignature returns the RequireSignature field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetRequireSignature() bool {
	if o == nil || o.RequireSignature == nil {
		var ret bool
		return ret
	}
	return *o.RequireSignature
}

// GetRequireSignatureOk returns a tuple with the RequireSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetRequireSignatureOk() (*bool, bool) {
	if o == nil || o.RequireSignature == nil {
		return nil, false
	}
	return o.RequireSignature, true
}

// HasRequireSignature returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasRequireSignature() bool {
	if o != nil && o.RequireSignature != nil {
		return true
	}

	return false
}

// SetRequireSignature gets a reference to the given bool and assigns it to the RequireSignature field.
func (o *OrdersShipmentViewModel) SetRequireSignature(v bool) {
	o.RequireSignature = &v
}

// GetShipOption returns the ShipOption field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetShipOption() string {
	if o == nil || o.ShipOption == nil {
		var ret string
		return ret
	}
	return *o.ShipOption
}

// GetShipOptionOk returns a tuple with the ShipOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetShipOptionOk() (*string, bool) {
	if o == nil || o.ShipOption == nil {
		return nil, false
	}
	return o.ShipOption, true
}

// HasShipOption returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasShipOption() bool {
	if o != nil && o.ShipOption != nil {
		return true
	}

	return false
}

// SetShipOption gets a reference to the given string and assigns it to the ShipOption field.
func (o *OrdersShipmentViewModel) SetShipOption(v string) {
	o.ShipOption = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OrdersShipmentViewModel) SetStatus(v string) {
	o.Status = &v
}

// GetStatusDetails returns the StatusDetails field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetStatusDetails() []OrdersStatusDetailViewModel {
	if o == nil || o.StatusDetails == nil {
		var ret []OrdersStatusDetailViewModel
		return ret
	}
	return *o.StatusDetails
}

// GetStatusDetailsOk returns a tuple with the StatusDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetStatusDetailsOk() (*[]OrdersStatusDetailViewModel, bool) {
	if o == nil || o.StatusDetails == nil {
		return nil, false
	}
	return o.StatusDetails, true
}

// HasStatusDetails returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasStatusDetails() bool {
	if o != nil && o.StatusDetails != nil {
		return true
	}

	return false
}

// SetStatusDetails gets a reference to the given []OrdersStatusDetailViewModel and assigns it to the StatusDetails field.
func (o *OrdersShipmentViewModel) SetStatusDetails(v []OrdersStatusDetailViewModel) {
	o.StatusDetails = &v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *OrdersShipmentViewModel) GetTracking() OrdersTrackingViewModel {
	if o == nil || o.Tracking == nil {
		var ret OrdersTrackingViewModel
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersShipmentViewModel) GetTrackingOk() (*OrdersTrackingViewModel, bool) {
	if o == nil || o.Tracking == nil {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *OrdersShipmentViewModel) HasTracking() bool {
	if o != nil && o.Tracking != nil {
		return true
	}

	return false
}

// SetTracking gets a reference to the given OrdersTrackingViewModel and assigns it to the Tracking field.
func (o *OrdersShipmentViewModel) SetTracking(v OrdersTrackingViewModel) {
	o.Tracking = &v
}

func (o OrdersShipmentViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActualFulfillmentDate.IsSet() {
		toSerialize["actual_fulfillment_date"] = o.ActualFulfillmentDate.Get()
	}
	if o.CreatedDate != nil {
		toSerialize["created_date"] = o.CreatedDate
	}
	if o.EstimatedFulfillmentDate.IsSet() {
		toSerialize["estimated_fulfillment_date"] = o.EstimatedFulfillmentDate.Get()
	}
	if o.EstimatedFulfillmentDateStatus != nil {
		toSerialize["estimated_fulfillment_date_status"] = o.EstimatedFulfillmentDateStatus
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.InsuranceValue.IsSet() {
		toSerialize["insurance_value"] = o.InsuranceValue.Get()
	}
	if o.InvoiceAmount.IsSet() {
		toSerialize["invoice_amount"] = o.InvoiceAmount.Get()
	}
	if o.LastUpdateAt.IsSet() {
		toSerialize["last_update_at"] = o.LastUpdateAt.Get()
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.Measurements != nil {
		toSerialize["measurements"] = o.Measurements
	}
	if o.OrderId != nil {
		toSerialize["order_id"] = o.OrderId
	}
	if o.PackageMaterialType != nil {
		toSerialize["package_material_type"] = o.PackageMaterialType
	}
	if o.Products != nil {
		toSerialize["products"] = o.Products
	}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	if o.ReferenceId != nil {
		toSerialize["reference_id"] = o.ReferenceId
	}
	if o.RequireSignature != nil {
		toSerialize["require_signature"] = o.RequireSignature
	}
	if o.ShipOption != nil {
		toSerialize["ship_option"] = o.ShipOption
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StatusDetails != nil {
		toSerialize["status_details"] = o.StatusDetails
	}
	if o.Tracking != nil {
		toSerialize["tracking"] = o.Tracking
	}
	return json.Marshal(toSerialize)
}

type NullableOrdersShipmentViewModel struct {
	value *OrdersShipmentViewModel
	isSet bool
}

func (v NullableOrdersShipmentViewModel) Get() *OrdersShipmentViewModel {
	return v.value
}

func (v *NullableOrdersShipmentViewModel) Set(val *OrdersShipmentViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersShipmentViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersShipmentViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersShipmentViewModel(val *OrdersShipmentViewModel) *NullableOrdersShipmentViewModel {
	return &NullableOrdersShipmentViewModel{value: val, isSet: true}
}

func (v NullableOrdersShipmentViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersShipmentViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


