/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// ShipbobProductsApiModelsPublicCreateProductModel The product to create
type ShipbobProductsApiModelsPublicCreateProductModel struct {
	// Barcode for the product
	Barcode NullableString `json:"barcode,omitempty"`
	// The name of the product
	Name NullableString `json:"name"`
	// Unique reference identifier for the product. Any linked or generated inventory will also be uniquely identified by this value
	ReferenceId NullableString `json:"reference_id"`
	// Stock keeping unit for the product
	Sku NullableString `json:"sku,omitempty"`
}

// NewShipbobProductsApiModelsPublicCreateProductModel instantiates a new ShipbobProductsApiModelsPublicCreateProductModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipbobProductsApiModelsPublicCreateProductModel(name NullableString, referenceId NullableString, ) *ShipbobProductsApiModelsPublicCreateProductModel {
	this := ShipbobProductsApiModelsPublicCreateProductModel{}
	this.Name = name
	this.ReferenceId = referenceId
	return &this
}

// NewShipbobProductsApiModelsPublicCreateProductModelWithDefaults instantiates a new ShipbobProductsApiModelsPublicCreateProductModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipbobProductsApiModelsPublicCreateProductModelWithDefaults() *ShipbobProductsApiModelsPublicCreateProductModel {
	this := ShipbobProductsApiModelsPublicCreateProductModel{}
	return &this
}

// GetBarcode returns the Barcode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetBarcode() string {
	if o == nil || o.Barcode.Get() == nil {
		var ret string
		return ret
	}
	return *o.Barcode.Get()
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetBarcodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Barcode.Get(), o.Barcode.IsSet()
}

// HasBarcode returns a boolean if a field has been set.
func (o *ShipbobProductsApiModelsPublicCreateProductModel) HasBarcode() bool {
	if o != nil && o.Barcode.IsSet() {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given NullableString and assigns it to the Barcode field.
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetBarcode(v string) {
	o.Barcode.Set(&v)
}
// SetBarcodeNil sets the value for Barcode to be an explicit nil
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetBarcodeNil() {
	o.Barcode.Set(nil)
}

// UnsetBarcode ensures that no value is present for Barcode, not even an explicit nil
func (o *ShipbobProductsApiModelsPublicCreateProductModel) UnsetBarcode() {
	o.Barcode.Unset()
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetName(v string) {
	o.Name.Set(&v)
}

// GetReferenceId returns the ReferenceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetReferenceId() string {
	if o == nil || o.ReferenceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ReferenceId.Get()
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetReferenceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ReferenceId.Get(), o.ReferenceId.IsSet()
}

// SetReferenceId sets field value
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetReferenceId(v string) {
	o.ReferenceId.Set(&v)
}

// GetSku returns the Sku field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetSku() string {
	if o == nil || o.Sku.Get() == nil {
		var ret string
		return ret
	}
	return *o.Sku.Get()
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipbobProductsApiModelsPublicCreateProductModel) GetSkuOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Sku.Get(), o.Sku.IsSet()
}

// HasSku returns a boolean if a field has been set.
func (o *ShipbobProductsApiModelsPublicCreateProductModel) HasSku() bool {
	if o != nil && o.Sku.IsSet() {
		return true
	}

	return false
}

// SetSku gets a reference to the given NullableString and assigns it to the Sku field.
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetSku(v string) {
	o.Sku.Set(&v)
}
// SetSkuNil sets the value for Sku to be an explicit nil
func (o *ShipbobProductsApiModelsPublicCreateProductModel) SetSkuNil() {
	o.Sku.Set(nil)
}

// UnsetSku ensures that no value is present for Sku, not even an explicit nil
func (o *ShipbobProductsApiModelsPublicCreateProductModel) UnsetSku() {
	o.Sku.Unset()
}

func (o ShipbobProductsApiModelsPublicCreateProductModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Barcode.IsSet() {
		toSerialize["barcode"] = o.Barcode.Get()
	}
	if true {
		toSerialize["name"] = o.Name.Get()
	}
	if true {
		toSerialize["reference_id"] = o.ReferenceId.Get()
	}
	if o.Sku.IsSet() {
		toSerialize["sku"] = o.Sku.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableShipbobProductsApiModelsPublicCreateProductModel struct {
	value *ShipbobProductsApiModelsPublicCreateProductModel
	isSet bool
}

func (v NullableShipbobProductsApiModelsPublicCreateProductModel) Get() *ShipbobProductsApiModelsPublicCreateProductModel {
	return v.value
}

func (v *NullableShipbobProductsApiModelsPublicCreateProductModel) Set(val *ShipbobProductsApiModelsPublicCreateProductModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShipbobProductsApiModelsPublicCreateProductModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShipbobProductsApiModelsPublicCreateProductModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipbobProductsApiModelsPublicCreateProductModel(val *ShipbobProductsApiModelsPublicCreateProductModel) *NullableShipbobProductsApiModelsPublicCreateProductModel {
	return &NullableShipbobProductsApiModelsPublicCreateProductModel{value: val, isSet: true}
}

func (v NullableShipbobProductsApiModelsPublicCreateProductModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipbobProductsApiModelsPublicCreateProductModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


