/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// ShipbobProductsApiViewModelsPublicInventoryItemViewModel The inventory that store products can resolve to when packing a shipment
type ShipbobProductsApiViewModelsPublicInventoryItemViewModel struct {
	// Unique id of the inventory item
	Id *int32 `json:"id,omitempty"`
	// Name of the inventory item
	Name NullableString `json:"name,omitempty"`
	// Quantity of the inventory item included in a store product
	Quantity *int32 `json:"quantity,omitempty"`
}

// NewShipbobProductsApiViewModelsPublicInventoryItemViewModel instantiates a new ShipbobProductsApiViewModelsPublicInventoryItemViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipbobProductsApiViewModelsPublicInventoryItemViewModel() *ShipbobProductsApiViewModelsPublicInventoryItemViewModel {
	this := ShipbobProductsApiViewModelsPublicInventoryItemViewModel{}
	return &this
}

// NewShipbobProductsApiViewModelsPublicInventoryItemViewModelWithDefaults instantiates a new ShipbobProductsApiViewModelsPublicInventoryItemViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipbobProductsApiViewModelsPublicInventoryItemViewModelWithDefaults() *ShipbobProductsApiViewModelsPublicInventoryItemViewModel {
	this := ShipbobProductsApiViewModelsPublicInventoryItemViewModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) UnsetName() {
	o.Name.Unset()
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetQuantity() int32 {
	if o == nil || o.Quantity == nil {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) GetQuantityOk() (*int32, bool) {
	if o == nil || o.Quantity == nil {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) HasQuantity() bool {
	if o != nil && o.Quantity != nil {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) SetQuantity(v int32) {
	o.Quantity = &v
}

func (o ShipbobProductsApiViewModelsPublicInventoryItemViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel struct {
	value *ShipbobProductsApiViewModelsPublicInventoryItemViewModel
	isSet bool
}

func (v NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) Get() *ShipbobProductsApiViewModelsPublicInventoryItemViewModel {
	return v.value
}

func (v *NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) Set(val *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipbobProductsApiViewModelsPublicInventoryItemViewModel(val *ShipbobProductsApiViewModelsPublicInventoryItemViewModel) *NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel {
	return &NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel{value: val, isSet: true}
}

func (v NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipbobProductsApiViewModelsPublicInventoryItemViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


