/*
ShipBob Developer API

ShipBob Developer API Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"fmt"
)

// GetLocations200ResponseInner - struct for GetLocations200ResponseInner
type GetLocations200ResponseInner struct {
	GetLocations200ResponseInnerOneOf *GetLocations200ResponseInnerOneOf
	InternalLocation                  *InternalLocation
	InternalLocationV2                *InternalLocationV2
}

// GetLocations200ResponseInnerOneOfAsGetLocations200ResponseInner is a convenience function that returns GetLocations200ResponseInnerOneOf wrapped in GetLocations200ResponseInner
func GetLocations200ResponseInnerOneOfAsGetLocations200ResponseInner(v *GetLocations200ResponseInnerOneOf) GetLocations200ResponseInner {
	return GetLocations200ResponseInner{
		GetLocations200ResponseInnerOneOf: v,
	}
}

// InternalLocationAsGetLocations200ResponseInner is a convenience function that returns InternalLocation wrapped in GetLocations200ResponseInner
func InternalLocationAsGetLocations200ResponseInner(v *InternalLocation) GetLocations200ResponseInner {
	return GetLocations200ResponseInner{
		InternalLocation: v,
	}
}

// InternalLocationV2AsGetLocations200ResponseInner is a convenience function that returns InternalLocationV2 wrapped in GetLocations200ResponseInner
func InternalLocationV2AsGetLocations200ResponseInner(v *InternalLocationV2) GetLocations200ResponseInner {
	return GetLocations200ResponseInner{
		InternalLocationV2: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetLocations200ResponseInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetLocations200ResponseInnerOneOf
	err = newStrictDecoder(data).Decode(&dst.GetLocations200ResponseInnerOneOf)
	if err == nil {
		jsonGetLocations200ResponseInnerOneOf, _ := json.Marshal(dst.GetLocations200ResponseInnerOneOf)
		if string(jsonGetLocations200ResponseInnerOneOf) == "{}" { // empty struct
			dst.GetLocations200ResponseInnerOneOf = nil
		} else {
			match++
		}
	} else {
		dst.GetLocations200ResponseInnerOneOf = nil
	}

	// try to unmarshal data into InternalLocation
	err = newStrictDecoder(data).Decode(&dst.InternalLocation)
	if err == nil {
		jsonInternalLocation, _ := json.Marshal(dst.InternalLocation)
		if string(jsonInternalLocation) == "{}" { // empty struct
			dst.InternalLocation = nil
		} else {
			match++
		}
	} else {
		dst.InternalLocation = nil
	}

	// try to unmarshal data into InternalLocationV2
	err = newStrictDecoder(data).Decode(&dst.InternalLocationV2)
	if err == nil {
		jsonInternalLocationV2, _ := json.Marshal(dst.InternalLocationV2)
		if string(jsonInternalLocationV2) == "{}" { // empty struct
			dst.InternalLocationV2 = nil
		} else {
			match++
		}
	} else {
		dst.InternalLocationV2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetLocations200ResponseInnerOneOf = nil
		dst.InternalLocation = nil
		dst.InternalLocationV2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetLocations200ResponseInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetLocations200ResponseInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetLocations200ResponseInner) MarshalJSON() ([]byte, error) {
	if src.GetLocations200ResponseInnerOneOf != nil {
		return json.Marshal(&src.GetLocations200ResponseInnerOneOf)
	}

	if src.InternalLocation != nil {
		return json.Marshal(&src.InternalLocation)
	}

	if src.InternalLocationV2 != nil {
		return json.Marshal(&src.InternalLocationV2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetLocations200ResponseInner) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.GetLocations200ResponseInnerOneOf != nil {
		return obj.GetLocations200ResponseInnerOneOf
	}

	if obj.InternalLocation != nil {
		return obj.InternalLocation
	}

	if obj.InternalLocationV2 != nil {
		return obj.InternalLocationV2
	}

	// all schemas are nil
	return nil
}

type NullableGetLocations200ResponseInner struct {
	value *GetLocations200ResponseInner
	isSet bool
}

func (v NullableGetLocations200ResponseInner) Get() *GetLocations200ResponseInner {
	return v.value
}

func (v *NullableGetLocations200ResponseInner) Set(val *GetLocations200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLocations200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLocations200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLocations200ResponseInner(val *GetLocations200ResponseInner) *NullableGetLocations200ResponseInner {
	return &NullableGetLocations200ResponseInner{value: val, isSet: true}
}

func (v NullableGetLocations200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLocations200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
