/*
ShipBob Developer API

ShipBob Developer API Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// checks if the ProductInventoryItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInventoryItem{}

// ProductInventoryItem The inventory that store products can resolve to when packing a shipment
type ProductInventoryItem struct {
	// Unique id of the inventory item
	Id *int32 `json:"id,omitempty"`
	// Name of the inventory item
	Name NullableString `json:"name,omitempty"`
	// Quantity of the inventory item included in a store product
	Quantity *int32 `json:"quantity,omitempty"`
}

// NewProductInventoryItem instantiates a new ProductInventoryItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInventoryItem() *ProductInventoryItem {
	this := ProductInventoryItem{}
	return &this
}

// NewProductInventoryItemWithDefaults instantiates a new ProductInventoryItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInventoryItemWithDefaults() *ProductInventoryItem {
	this := ProductInventoryItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductInventoryItem) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInventoryItem) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductInventoryItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProductInventoryItem) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInventoryItem) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInventoryItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ProductInventoryItem) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ProductInventoryItem) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ProductInventoryItem) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ProductInventoryItem) UnsetName() {
	o.Name.Unset()
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ProductInventoryItem) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInventoryItem) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ProductInventoryItem) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *ProductInventoryItem) SetQuantity(v int32) {
	o.Quantity = &v
}

func (o ProductInventoryItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInventoryItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableProductInventoryItem struct {
	value *ProductInventoryItem
	isSet bool
}

func (v NullableProductInventoryItem) Get() *ProductInventoryItem {
	return v.value
}

func (v *NullableProductInventoryItem) Set(val *ProductInventoryItem) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInventoryItem) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInventoryItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInventoryItem(val *ProductInventoryItem) *NullableProductInventoryItem {
	return &NullableProductInventoryItem{value: val, isSet: true}
}

func (v NullableProductInventoryItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInventoryItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
