/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// CanceledShipment struct for CanceledShipment
type CanceledShipment struct {
	Action *string `json:"action,omitempty"`
	// If the cancel action was successfull
	IsSuccess *bool `json:"is_success,omitempty"`
	// The reason the cancellation result
	Reason *string `json:"reason,omitempty"`
	// The ID of the shipment
	ShipmentId *int64 `json:"shipment_id,omitempty"`
}

// NewCanceledShipment instantiates a new CanceledShipment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanceledShipment() *CanceledShipment {
	this := CanceledShipment{}
	return &this
}

// NewCanceledShipmentWithDefaults instantiates a new CanceledShipment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanceledShipmentWithDefaults() *CanceledShipment {
	this := CanceledShipment{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *CanceledShipment) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanceledShipment) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *CanceledShipment) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *CanceledShipment) SetAction(v string) {
	o.Action = &v
}

// GetIsSuccess returns the IsSuccess field value if set, zero value otherwise.
func (o *CanceledShipment) GetIsSuccess() bool {
	if o == nil || o.IsSuccess == nil {
		var ret bool
		return ret
	}
	return *o.IsSuccess
}

// GetIsSuccessOk returns a tuple with the IsSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanceledShipment) GetIsSuccessOk() (*bool, bool) {
	if o == nil || o.IsSuccess == nil {
		return nil, false
	}
	return o.IsSuccess, true
}

// HasIsSuccess returns a boolean if a field has been set.
func (o *CanceledShipment) HasIsSuccess() bool {
	if o != nil && o.IsSuccess != nil {
		return true
	}

	return false
}

// SetIsSuccess gets a reference to the given bool and assigns it to the IsSuccess field.
func (o *CanceledShipment) SetIsSuccess(v bool) {
	o.IsSuccess = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CanceledShipment) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanceledShipment) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CanceledShipment) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CanceledShipment) SetReason(v string) {
	o.Reason = &v
}

// GetShipmentId returns the ShipmentId field value if set, zero value otherwise.
func (o *CanceledShipment) GetShipmentId() int64 {
	if o == nil || o.ShipmentId == nil {
		var ret int64
		return ret
	}
	return *o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanceledShipment) GetShipmentIdOk() (*int64, bool) {
	if o == nil || o.ShipmentId == nil {
		return nil, false
	}
	return o.ShipmentId, true
}

// HasShipmentId returns a boolean if a field has been set.
func (o *CanceledShipment) HasShipmentId() bool {
	if o != nil && o.ShipmentId != nil {
		return true
	}

	return false
}

// SetShipmentId gets a reference to the given int64 and assigns it to the ShipmentId field.
func (o *CanceledShipment) SetShipmentId(v int64) {
	o.ShipmentId = &v
}

func (o CanceledShipment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.IsSuccess != nil {
		toSerialize["is_success"] = o.IsSuccess
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.ShipmentId != nil {
		toSerialize["shipment_id"] = o.ShipmentId
	}
	return json.Marshal(toSerialize)
}

type NullableCanceledShipment struct {
	value *CanceledShipment
	isSet bool
}

func (v NullableCanceledShipment) Get() *CanceledShipment {
	return v.value
}

func (v *NullableCanceledShipment) Set(val *CanceledShipment) {
	v.value = val
	v.isSet = true
}

func (v NullableCanceledShipment) IsSet() bool {
	return v.isSet
}

func (v *NullableCanceledShipment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanceledShipment(val *CanceledShipment) *NullableCanceledShipment {
	return &NullableCanceledShipment{value: val, isSet: true}
}

func (v NullableCanceledShipment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanceledShipment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
