/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// ShipBobOrdersPresentationViewModelsChannelInfoViewModel Created by channel metadata
type ShipBobOrdersPresentationViewModelsChannelInfoViewModel struct {
	// Unique id of the channel
	Id *int32 `json:"id,omitempty"`
	// Name of the channel
	Name *string `json:"name,omitempty"`
}

// NewShipBobOrdersPresentationViewModelsChannelInfoViewModel instantiates a new ShipBobOrdersPresentationViewModelsChannelInfoViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipBobOrdersPresentationViewModelsChannelInfoViewModel() *ShipBobOrdersPresentationViewModelsChannelInfoViewModel {
	this := ShipBobOrdersPresentationViewModelsChannelInfoViewModel{}
	return &this
}

// NewShipBobOrdersPresentationViewModelsChannelInfoViewModelWithDefaults instantiates a new ShipBobOrdersPresentationViewModelsChannelInfoViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipBobOrdersPresentationViewModelsChannelInfoViewModelWithDefaults() *ShipBobOrdersPresentationViewModelsChannelInfoViewModel {
	this := ShipBobOrdersPresentationViewModelsChannelInfoViewModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) SetName(v string) {
	o.Name = &v
}

func (o ShipBobOrdersPresentationViewModelsChannelInfoViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel struct {
	value *ShipBobOrdersPresentationViewModelsChannelInfoViewModel
	isSet bool
}

func (v NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) Get() *ShipBobOrdersPresentationViewModelsChannelInfoViewModel {
	return v.value
}

func (v *NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) Set(val *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipBobOrdersPresentationViewModelsChannelInfoViewModel(val *ShipBobOrdersPresentationViewModelsChannelInfoViewModel) *NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel {
	return &NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel{value: val, isSet: true}
}

func (v NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipBobOrdersPresentationViewModelsChannelInfoViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


