/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"fmt"
)

// ShipbobReturnsPublicCommonReturnStatus the model 'ShipbobReturnsPublicCommonReturnStatus'
type ShipbobReturnsPublicCommonReturnStatus string

// List of Shipbob.Returns.Public.Common.ReturnStatus
const (
	AWAITING_ARRIVAL ShipbobReturnsPublicCommonReturnStatus = "AwaitingArrival"
	ARRIVED ShipbobReturnsPublicCommonReturnStatus = "Arrived"
	PROCESSING ShipbobReturnsPublicCommonReturnStatus = "Processing"
	COMPLETED ShipbobReturnsPublicCommonReturnStatus = "Completed"
	CANCELLED ShipbobReturnsPublicCommonReturnStatus = "Cancelled"
)

func (v *ShipbobReturnsPublicCommonReturnStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShipbobReturnsPublicCommonReturnStatus(value)
	for _, existing := range []ShipbobReturnsPublicCommonReturnStatus{ "AwaitingArrival", "Arrived", "Processing", "Completed", "Cancelled",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShipbobReturnsPublicCommonReturnStatus", value)
}

// Ptr returns reference to Shipbob.Returns.Public.Common.ReturnStatus value
func (v ShipbobReturnsPublicCommonReturnStatus) Ptr() *ShipbobReturnsPublicCommonReturnStatus {
	return &v
}

type NullableShipbobReturnsPublicCommonReturnStatus struct {
	value *ShipbobReturnsPublicCommonReturnStatus
	isSet bool
}

func (v NullableShipbobReturnsPublicCommonReturnStatus) Get() *ShipbobReturnsPublicCommonReturnStatus {
	return v.value
}

func (v *NullableShipbobReturnsPublicCommonReturnStatus) Set(val *ShipbobReturnsPublicCommonReturnStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableShipbobReturnsPublicCommonReturnStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableShipbobReturnsPublicCommonReturnStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipbobReturnsPublicCommonReturnStatus(val *ShipbobReturnsPublicCommonReturnStatus) *NullableShipbobReturnsPublicCommonReturnStatus {
	return &NullableShipbobReturnsPublicCommonReturnStatus{value: val, isSet: true}
}

func (v NullableShipbobReturnsPublicCommonReturnStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipbobReturnsPublicCommonReturnStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

