/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"fmt"
)

// ShipbobReceivingPublicCommonModelsPackingType the model 'ShipbobReceivingPublicCommonModelsPackingType'
type ShipbobReceivingPublicCommonModelsPackingType string

// List of Shipbob.Receiving.Public.Common.Models.PackingType
const (
	EVERYTHING_IN_ONE_BOX ShipbobReceivingPublicCommonModelsPackingType = "EverythingInOneBox"
	ONE_SKU_PER_BOX ShipbobReceivingPublicCommonModelsPackingType = "OneSkuPerBox"
	MULTIPLE_SKU_PER_BOX ShipbobReceivingPublicCommonModelsPackingType = "MultipleSkuPerBox"
)

func (v *ShipbobReceivingPublicCommonModelsPackingType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShipbobReceivingPublicCommonModelsPackingType(value)
	for _, existing := range []ShipbobReceivingPublicCommonModelsPackingType{ "EverythingInOneBox", "OneSkuPerBox", "MultipleSkuPerBox",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShipbobReceivingPublicCommonModelsPackingType", value)
}

// Ptr returns reference to Shipbob.Receiving.Public.Common.Models.PackingType value
func (v ShipbobReceivingPublicCommonModelsPackingType) Ptr() *ShipbobReceivingPublicCommonModelsPackingType {
	return &v
}

type NullableShipbobReceivingPublicCommonModelsPackingType struct {
	value *ShipbobReceivingPublicCommonModelsPackingType
	isSet bool
}

func (v NullableShipbobReceivingPublicCommonModelsPackingType) Get() *ShipbobReceivingPublicCommonModelsPackingType {
	return v.value
}

func (v *NullableShipbobReceivingPublicCommonModelsPackingType) Set(val *ShipbobReceivingPublicCommonModelsPackingType) {
	v.value = val
	v.isSet = true
}

func (v NullableShipbobReceivingPublicCommonModelsPackingType) IsSet() bool {
	return v.isSet
}

func (v *NullableShipbobReceivingPublicCommonModelsPackingType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipbobReceivingPublicCommonModelsPackingType(val *ShipbobReceivingPublicCommonModelsPackingType) *NullableShipbobReceivingPublicCommonModelsPackingType {
	return &NullableShipbobReceivingPublicCommonModelsPackingType{value: val, isSet: true}
}

func (v NullableShipbobReceivingPublicCommonModelsPackingType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipbobReceivingPublicCommonModelsPackingType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

