/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"time"
)

// OrdersCreateOrderModel struct for OrdersCreateOrderModel
type OrdersCreateOrderModel struct {
	// User friendly orderId or store order number that will be shown on the Orders Page. If not provided, referenceId will be used
	OrderNumber *string `json:"order_number,omitempty"`
	Products []OrdersAddProductToOrderModel `json:"products"`
	// Date this order was purchase by the end user
	PurchaseDate NullableTime `json:"purchase_date,omitempty"`
	Recipient OrdersRecipientInfoViewModel `json:"recipient"`
	ReferenceId string `json:"reference_id"`
	ShippingMethod string `json:"shipping_method"`
	Tags *[]OrdersTagViewModel `json:"tags,omitempty"`
	// Defaults to Direct to Consumer (DTC) if not provided. Note: B2B is not supported at this time
	Type *string `json:"type,omitempty"`
}

// NewOrdersCreateOrderModel instantiates a new OrdersCreateOrderModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersCreateOrderModel(products []OrdersAddProductToOrderModel, recipient OrdersRecipientInfoViewModel, referenceId string, shippingMethod string, ) *OrdersCreateOrderModel {
	this := OrdersCreateOrderModel{}
	this.Products = products
	this.Recipient = recipient
	this.ReferenceId = referenceId
	this.ShippingMethod = shippingMethod
	return &this
}

// NewOrdersCreateOrderModelWithDefaults instantiates a new OrdersCreateOrderModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersCreateOrderModelWithDefaults() *OrdersCreateOrderModel {
	this := OrdersCreateOrderModel{}
	return &this
}

// GetOrderNumber returns the OrderNumber field value if set, zero value otherwise.
func (o *OrdersCreateOrderModel) GetOrderNumber() string {
	if o == nil || o.OrderNumber == nil {
		var ret string
		return ret
	}
	return *o.OrderNumber
}

// GetOrderNumberOk returns a tuple with the OrderNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetOrderNumberOk() (*string, bool) {
	if o == nil || o.OrderNumber == nil {
		return nil, false
	}
	return o.OrderNumber, true
}

// HasOrderNumber returns a boolean if a field has been set.
func (o *OrdersCreateOrderModel) HasOrderNumber() bool {
	if o != nil && o.OrderNumber != nil {
		return true
	}

	return false
}

// SetOrderNumber gets a reference to the given string and assigns it to the OrderNumber field.
func (o *OrdersCreateOrderModel) SetOrderNumber(v string) {
	o.OrderNumber = &v
}

// GetProducts returns the Products field value
func (o *OrdersCreateOrderModel) GetProducts() []OrdersAddProductToOrderModel {
	if o == nil  {
		var ret []OrdersAddProductToOrderModel
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetProductsOk() (*[]OrdersAddProductToOrderModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Products, true
}

// SetProducts sets field value
func (o *OrdersCreateOrderModel) SetProducts(v []OrdersAddProductToOrderModel) {
	o.Products = v
}

// GetPurchaseDate returns the PurchaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrdersCreateOrderModel) GetPurchaseDate() time.Time {
	if o == nil || o.PurchaseDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.PurchaseDate.Get()
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrdersCreateOrderModel) GetPurchaseDateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PurchaseDate.Get(), o.PurchaseDate.IsSet()
}

// HasPurchaseDate returns a boolean if a field has been set.
func (o *OrdersCreateOrderModel) HasPurchaseDate() bool {
	if o != nil && o.PurchaseDate.IsSet() {
		return true
	}

	return false
}

// SetPurchaseDate gets a reference to the given NullableTime and assigns it to the PurchaseDate field.
func (o *OrdersCreateOrderModel) SetPurchaseDate(v time.Time) {
	o.PurchaseDate.Set(&v)
}
// SetPurchaseDateNil sets the value for PurchaseDate to be an explicit nil
func (o *OrdersCreateOrderModel) SetPurchaseDateNil() {
	o.PurchaseDate.Set(nil)
}

// UnsetPurchaseDate ensures that no value is present for PurchaseDate, not even an explicit nil
func (o *OrdersCreateOrderModel) UnsetPurchaseDate() {
	o.PurchaseDate.Unset()
}

// GetRecipient returns the Recipient field value
func (o *OrdersCreateOrderModel) GetRecipient() OrdersRecipientInfoViewModel {
	if o == nil  {
		var ret OrdersRecipientInfoViewModel
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetRecipientOk() (*OrdersRecipientInfoViewModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *OrdersCreateOrderModel) SetRecipient(v OrdersRecipientInfoViewModel) {
	o.Recipient = v
}

// GetReferenceId returns the ReferenceId field value
func (o *OrdersCreateOrderModel) GetReferenceId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetReferenceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *OrdersCreateOrderModel) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetShippingMethod returns the ShippingMethod field value
func (o *OrdersCreateOrderModel) GetShippingMethod() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ShippingMethod
}

// GetShippingMethodOk returns a tuple with the ShippingMethod field value
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetShippingMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShippingMethod, true
}

// SetShippingMethod sets field value
func (o *OrdersCreateOrderModel) SetShippingMethod(v string) {
	o.ShippingMethod = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *OrdersCreateOrderModel) GetTags() []OrdersTagViewModel {
	if o == nil || o.Tags == nil {
		var ret []OrdersTagViewModel
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetTagsOk() (*[]OrdersTagViewModel, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *OrdersCreateOrderModel) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []OrdersTagViewModel and assigns it to the Tags field.
func (o *OrdersCreateOrderModel) SetTags(v []OrdersTagViewModel) {
	o.Tags = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrdersCreateOrderModel) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersCreateOrderModel) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrdersCreateOrderModel) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrdersCreateOrderModel) SetType(v string) {
	o.Type = &v
}

func (o OrdersCreateOrderModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderNumber != nil {
		toSerialize["order_number"] = o.OrderNumber
	}
	if true {
		toSerialize["products"] = o.Products
	}
	if o.PurchaseDate.IsSet() {
		toSerialize["purchase_date"] = o.PurchaseDate.Get()
	}
	if true {
		toSerialize["recipient"] = o.Recipient
	}
	if true {
		toSerialize["reference_id"] = o.ReferenceId
	}
	if true {
		toSerialize["shipping_method"] = o.ShippingMethod
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableOrdersCreateOrderModel struct {
	value *OrdersCreateOrderModel
	isSet bool
}

func (v NullableOrdersCreateOrderModel) Get() *OrdersCreateOrderModel {
	return v.value
}

func (v *NullableOrdersCreateOrderModel) Set(val *OrdersCreateOrderModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersCreateOrderModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersCreateOrderModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersCreateOrderModel(val *OrdersCreateOrderModel) *NullableOrdersCreateOrderModel {
	return &NullableOrdersCreateOrderModel{value: val, isSet: true}
}

func (v NullableOrdersCreateOrderModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersCreateOrderModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


