/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// ShipBobOrdersPresentationViewModelsEstimateViewModel struct for ShipBobOrdersPresentationViewModelsEstimateViewModel
type ShipBobOrdersPresentationViewModelsEstimateViewModel struct {
	// Array of estimates for each shipping method
	Estimates *[]ShipBobOrdersPresentationViewModelsEstimateDetailViewModel `json:"estimates,omitempty"`
}

// NewShipBobOrdersPresentationViewModelsEstimateViewModel instantiates a new ShipBobOrdersPresentationViewModelsEstimateViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipBobOrdersPresentationViewModelsEstimateViewModel() *ShipBobOrdersPresentationViewModelsEstimateViewModel {
	this := ShipBobOrdersPresentationViewModelsEstimateViewModel{}
	return &this
}

// NewShipBobOrdersPresentationViewModelsEstimateViewModelWithDefaults instantiates a new ShipBobOrdersPresentationViewModelsEstimateViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipBobOrdersPresentationViewModelsEstimateViewModelWithDefaults() *ShipBobOrdersPresentationViewModelsEstimateViewModel {
	this := ShipBobOrdersPresentationViewModelsEstimateViewModel{}
	return &this
}

// GetEstimates returns the Estimates field value if set, zero value otherwise.
func (o *ShipBobOrdersPresentationViewModelsEstimateViewModel) GetEstimates() []ShipBobOrdersPresentationViewModelsEstimateDetailViewModel {
	if o == nil || o.Estimates == nil {
		var ret []ShipBobOrdersPresentationViewModelsEstimateDetailViewModel
		return ret
	}
	return *o.Estimates
}

// GetEstimatesOk returns a tuple with the Estimates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipBobOrdersPresentationViewModelsEstimateViewModel) GetEstimatesOk() (*[]ShipBobOrdersPresentationViewModelsEstimateDetailViewModel, bool) {
	if o == nil || o.Estimates == nil {
		return nil, false
	}
	return o.Estimates, true
}

// HasEstimates returns a boolean if a field has been set.
func (o *ShipBobOrdersPresentationViewModelsEstimateViewModel) HasEstimates() bool {
	if o != nil && o.Estimates != nil {
		return true
	}

	return false
}

// SetEstimates gets a reference to the given []ShipBobOrdersPresentationViewModelsEstimateDetailViewModel and assigns it to the Estimates field.
func (o *ShipBobOrdersPresentationViewModelsEstimateViewModel) SetEstimates(v []ShipBobOrdersPresentationViewModelsEstimateDetailViewModel) {
	o.Estimates = &v
}

func (o ShipBobOrdersPresentationViewModelsEstimateViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Estimates != nil {
		toSerialize["estimates"] = o.Estimates
	}
	return json.Marshal(toSerialize)
}

type NullableShipBobOrdersPresentationViewModelsEstimateViewModel struct {
	value *ShipBobOrdersPresentationViewModelsEstimateViewModel
	isSet bool
}

func (v NullableShipBobOrdersPresentationViewModelsEstimateViewModel) Get() *ShipBobOrdersPresentationViewModelsEstimateViewModel {
	return v.value
}

func (v *NullableShipBobOrdersPresentationViewModelsEstimateViewModel) Set(val *ShipBobOrdersPresentationViewModelsEstimateViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShipBobOrdersPresentationViewModelsEstimateViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShipBobOrdersPresentationViewModelsEstimateViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipBobOrdersPresentationViewModelsEstimateViewModel(val *ShipBobOrdersPresentationViewModelsEstimateViewModel) *NullableShipBobOrdersPresentationViewModelsEstimateViewModel {
	return &NullableShipBobOrdersPresentationViewModelsEstimateViewModel{value: val, isSet: true}
}

func (v NullableShipBobOrdersPresentationViewModelsEstimateViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipBobOrdersPresentationViewModelsEstimateViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


