/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// OrdersRecipientViewModel Information about the recipient of a shipment
type OrdersRecipientViewModel struct {
	Address *OrdersAddressViewModel `json:"address,omitempty"`
	// Email address of the recipient
	Email *string `json:"email,omitempty"`
	// Name of the recipient
	Name *string `json:"name,omitempty"`
	// Phone number of the recipient
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// NewOrdersRecipientViewModel instantiates a new OrdersRecipientViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersRecipientViewModel() *OrdersRecipientViewModel {
	this := OrdersRecipientViewModel{}
	return &this
}

// NewOrdersRecipientViewModelWithDefaults instantiates a new OrdersRecipientViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersRecipientViewModelWithDefaults() *OrdersRecipientViewModel {
	this := OrdersRecipientViewModel{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *OrdersRecipientViewModel) GetAddress() OrdersAddressViewModel {
	if o == nil || o.Address == nil {
		var ret OrdersAddressViewModel
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersRecipientViewModel) GetAddressOk() (*OrdersAddressViewModel, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *OrdersRecipientViewModel) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given OrdersAddressViewModel and assigns it to the Address field.
func (o *OrdersRecipientViewModel) SetAddress(v OrdersAddressViewModel) {
	o.Address = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OrdersRecipientViewModel) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersRecipientViewModel) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OrdersRecipientViewModel) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OrdersRecipientViewModel) SetEmail(v string) {
	o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrdersRecipientViewModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersRecipientViewModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrdersRecipientViewModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrdersRecipientViewModel) SetName(v string) {
	o.Name = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *OrdersRecipientViewModel) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersRecipientViewModel) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *OrdersRecipientViewModel) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *OrdersRecipientViewModel) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o OrdersRecipientViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	return json.Marshal(toSerialize)
}

type NullableOrdersRecipientViewModel struct {
	value *OrdersRecipientViewModel
	isSet bool
}

func (v NullableOrdersRecipientViewModel) Get() *OrdersRecipientViewModel {
	return v.value
}

func (v *NullableOrdersRecipientViewModel) Set(val *OrdersRecipientViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersRecipientViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersRecipientViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersRecipientViewModel(val *OrdersRecipientViewModel) *NullableOrdersRecipientViewModel {
	return &NullableOrdersRecipientViewModel{value: val, isSet: true}
}

func (v NullableOrdersRecipientViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersRecipientViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


