/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
	"fmt"
)

// ReturnsReturnAction the model 'ReturnsReturnAction'
type ReturnsReturnAction string

// List of Returns.ReturnAction
const (
	ReturnsReturnActionDEFAULT ReturnsReturnAction = "Default"
	ReturnsReturnActionRESTOCK ReturnsReturnAction = "Restock"
	ReturnsReturnActionQUARANTINE ReturnsReturnAction = "Quarantine"
	ReturnsReturnActionDISPOSE ReturnsReturnAction = "Dispose"
)

func (v *ReturnsReturnAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReturnsReturnAction(value)
	for _, existing := range []ReturnsReturnAction{ "Default", "Restock", "Quarantine", "Dispose",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReturnsReturnAction", value)
}

// Ptr returns reference to Returns.ReturnAction value
func (v ReturnsReturnAction) Ptr() *ReturnsReturnAction {
	return &v
}

type NullableReturnsReturnAction struct {
	value *ReturnsReturnAction
	isSet bool
}

func (v NullableReturnsReturnAction) Get() *ReturnsReturnAction {
	return v.value
}

func (v *NullableReturnsReturnAction) Set(val *ReturnsReturnAction) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnsReturnAction) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnsReturnAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnsReturnAction(val *ReturnsReturnAction) *NullableReturnsReturnAction {
	return &NullableReturnsReturnAction{value: val, isSet: true}
}

func (v NullableReturnsReturnAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnsReturnAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

