/*
 * ShipBob Developer API
 *
 * ShipBob Developer API Documentation
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipbob

import (
	"encoding/json"
)

// OrdersTagViewModel struct for OrdersTagViewModel
type OrdersTagViewModel struct {
	// The key of the tag
	Name string `json:"name"`
	// The value of the tag
	Value string `json:"value"`
}

// NewOrdersTagViewModel instantiates a new OrdersTagViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersTagViewModel(name string, value string, ) *OrdersTagViewModel {
	this := OrdersTagViewModel{}
	this.Name = name
	this.Value = value
	return &this
}

// NewOrdersTagViewModelWithDefaults instantiates a new OrdersTagViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersTagViewModelWithDefaults() *OrdersTagViewModel {
	this := OrdersTagViewModel{}
	return &this
}

// GetName returns the Name field value
func (o *OrdersTagViewModel) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrdersTagViewModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrdersTagViewModel) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *OrdersTagViewModel) GetValue() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *OrdersTagViewModel) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *OrdersTagViewModel) SetValue(v string) {
	o.Value = v
}

func (o OrdersTagViewModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableOrdersTagViewModel struct {
	value *OrdersTagViewModel
	isSet bool
}

func (v NullableOrdersTagViewModel) Get() *OrdersTagViewModel {
	return v.value
}

func (v *NullableOrdersTagViewModel) Set(val *OrdersTagViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersTagViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersTagViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersTagViewModel(val *OrdersTagViewModel) *NullableOrdersTagViewModel {
	return &NullableOrdersTagViewModel{value: val, isSet: true}
}

func (v NullableOrdersTagViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersTagViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


