openapi: 3.0.1
info:
  description: ShipBob Developer API Documentation
  title: ShipBob Developer API
  version: "1.0"
servers:
- url: https://api.shipbob.com/1.0/
tags:
- description: ' >  Note: The orderId in the API response will not match the Id displayed
    in the ShipBob Merchant Portal when you navigate to the Orders page. ShipBob is
    currently undergoing a schema migration and the Id displayed in the ShipBob Merchant
    Portal is the shipmentId not the orderId. In the future, the portal will display
    both orderId(s) and shipmentId(s).  Use the Orders Resource to create and retrieve
    orders in ShipBob.  An order a digital record of a complete purchase that comes
    from an upstream source (i.e. Shopify) and is intended for ShipBob to fulfill.
    The order object includes products purchased, shipping address details, shipping
    method selected etc. Orders are created in ShipBob via a channel.  When ShipBob
    fulfills the order, one or more shipments are created for that order. A shipment
    is a record of the physical package(s) sent out via a carrier. If an order is
    shipped in multiple packages then 2 or more shipments can be created for that
    order.  ### Tips for creating orders in ShipBob via the POST Order endpoint:  *
    Populate the referenceId with a unique and immutable order identifier from your
    upstream system. This field was created to allow you to tieback records in ShipBob
    with your upstream system.  * Ensure that the <em> shipping method </em> passed
    in the API request matches exactly what the user has listed as the <em> shipping
    method </em> on the <em>  Ship Option Mapping </em> setup page in the ShipBob
    Merchant Portal. If they don''t match, ShipBob will assume that the user wants
    to leverage ShipBob''s default shipping method.  * You can leverage either productId
    (the ShipBob productId) or the product referenceId (your system''s  unique Identifier
    for products) when creating an order.  Use the Shipments endpoints to retrieve
    fulfillment information for shipments or orders.  A shipment is an object that
    is the result of a fulfillment of an order. An order can have one or more shipments.
    Say Shopify order #122323 contains 3 different products, shipped in two separate
    packages, there would be 2 shipments for that order.   Serial numbers are unique
    identifiers for an individual item (e.g. your specific iPhone X that you bought
    at the Apple Store). No inventory item can possess duplicate serial numbers. Merchants
    can request serial scan, which means ShipBob will capture the serial number(s)
    upon sending a shipment so the merchant knows which customer received which individual
    item(s).'
  name: Orders
- description: 'Use the Products Resource to retrieve and create product records in
    ShipBob.  A product is a virtual record created in ShipBob''s system via a channel.
    Say a merchant has two Shopify stores (each store would have its own channel),
    Kevin''s Shopify Store #133 and Kevin''s Shopify store #134. If the same SKU was
    sold on both stores, two products would be created for that SKU, one product would
    be created to represent the SKU sold on Store #133 and one to represent it on
    Store on #134, with productIds 3884009 and 3884008 respectively.  While a product
    is a virtual record, the inventory item is a representation of a physical good.
    So in the above example, as product 3884009 and product 3884008 represent the
    same SKU sold on different channels, the same inventory item will be mapped to
    both products. Every product will have one or more inventory items mapped to it.
    Bundle products, a set of products that are sold to consumers as one combined
    package, think gift or multi packs, may have 2 or more inventory items mapped
    to them.  ### Tips for creating products in ShipBob via the POST Product endpoints:  *
    ShipBob needs products to be created at the lowest level. So if a product has
    3 variants, small, medium and large, a separate product needs to be created in
    ShipBob for all three. * Populate the referenceId with a unique and immutable
    product identifier from your upstream system. This field was created to allow
    you to tie back records in ShipBob with your upstream system.  * Use specific
    and/or unique names to describe each product so they can be easily identified
    by users in the ShipBob Merchant Portal. In particular, when creating variants,
    please give them distinguishable names i.e. for a Blue shirt that comes in two
    sizes, small and medium, strong product names would be Blue shirt size:small and
    Blue shirt size:medium.  > **NOTE:** The productId returned in the API response
    will not match the id displayed in the ShipBob Merchant Portal when you navigate
    to Inventory > Products. ShipBob is currently undergoing a schema migration and
    the Id displayed in the ShipBob Merchant Portal is the inventoryId not the productId.
    In the future, the portal will display both productId(s) and inventoryId(s)'
  name: Products
- description: ' Use the Inventory Resource to retrieve ShipBob  inventory items and
    quantities.  An inventory item is a representation of a physical good, that may
    or may not have physical stock in ShipBob''s fulfillment centers. Every product
    will have one or more inventory items mapped to it. A bundle product (a set of
    products that are sold as one combined package - e.g.  gift or multi packs) is
    an example of a product that has  2 or more inventory items mapped to it.  Lot
    items are physical items that have expiration dates or batch numbers that should
    be fulfilled in a FIFO (first in, first out) manner. Most food items are lot items.
    Quantities by lot # and/or expiration date are also listed in the Inventory object.'
  name: Inventory
- description: 'Use the Channel Resource to list channels which you have access to.
    You will use this channelId for subsequent API calls made to ShipBob endpoints.  A
    channel is a specific installation of an application built by a vendor on top
    of our API e.g. Kevin''s Shopify Store #133432.  All write and most read endpoints
    require a channel to be passed in the header to complete the request. The channel
    is used to Identify where the data originally came from.   Applications that are
    granted multi-channel permissions will be able to read data from all channels
    that belong to a user. However, multi-channel applications will only be able to
    write on behalf of their own channel.'
  name: Channels
- description: '**While the Returns API is live, ShipBob''s end to end Returns process
    will not go live until the beginning of March. As a result, any returns arriving
    at ShipBob''s fulfillment centers prior to March 12st, 2020 will NOT be processed**.  Use
    the Returns resource to retrieve, create, edit and cancel return records in ShipBob.  A
    return is a request for ShipBob to perform an action on inventory that is coming
    back into our fulfillment centers. Typically, the return is a result of an order
    being requested to be refunded or exchanged. ShipBob does not handle refunds or
    exchanges - we simply process the inventory according to the merchant specifications.  Returns
    can only be **modified** or **cancelled** when they are in the Awaiting Arrival
    status. Returns that are being Processed or have been Completed cannot be modified
    or cancelled.  ### Tips for creating return orders:  * Populate the referenceId
    with a unique and immutable return identifier from your upstream system. This
    field was created to allow you to tie back records in ShipBob with your upstream
    system.  *Include each inventoryId exactly once in the inventory object. If an
    inventoryId is included more than once, the call will return an error code  *
    Provide a tracking # when submitting a return, while it is not a required field,
    it is the the most surefire way for ShipBob staff to properly and quickly identify
    the return package when it reaches our fulfillment center.  * Only include inventory
    items to the return record that will be returned in the same box i.e. if InventoryId
    12232 and InventoryId 12039 will be returned in two seperate boxes, two return
    orders should be created.  * ShipBob does not process returns for digital items
    or bundle inventory items. Return calls that include digital inventory  items
    (e.g. ebooks) or bundle inventory items (i.e. multipacks, combination of multiple
    inventory items)  will return an error code.  * If you choose to provide a requested
    action (it is an optional field), only provide one requested action per inventory
    item. So if  you have more than 1 quantity of a given item being returned within
    the same box, all quantities of the item have to have the same action associated
    with them. If you don''t provide a requested action, it will default to the action
    the User set for that inventory item in the ShipBob Merchant portal.'
  name: Returns
- description: Use the Receiving Resource to retrieve, create and cancel Warehouse
    Receiving Orders (WROs).  A WRO is a request form that tells ShipBob's fulfillment
    centers what inventory should be received and stocked. Some other solutions call
    this an ASN or Advanced Ship Notice. WROs may include multiple inventory items
    with specific quantities. More details on creating a WRO can be found [here](https://support.shipbob.com/s/article/New-Send-Inventory-to-ShipBob-WRO).  A
    WRO can only be **canceled** if it is in the Awaiting status. WROs in Awaiting
    status are considered to still be in transit to ShipBob FCs. WROs that have Partially
    Arrived, have been Processed or are Completed, cannot be canceled.
  name: Receiving
- description: Use the Webhooks Resource to create, view or delete subscriptions for
    a user.
  name: Webhooks
- description: Use this API to interact with the physical locations across ShipBob's
    fulfillment network.  An active ShipBob location is operational for fulfillment
    processes, including receiving inventory and processing returns. It's important
    to note that some locations, access is granted to all merchants by default, while
    some locations require special request for merchants to be granted access.  For
    each location, determine if it can be leveraged for the user by viewing the access_granted
    & receiving_enabled fields.
  name: Locations
paths:
  /channel:
    get:
      operationId: getChannels
      security:
      - oauth2:
        - HasChannelIdPermissions
      summary: Get user-authorized channel info
      tags:
      - Channels
  /fulfillmentCenter:
    get:
      operationId: getFulfillmentCenters
      security:
      - oauth2:
        - receiving_read
      summary: Get Fulfillment Centers
      tags:
      - Receiving
  /inventory:
    get:
      operationId: getInventories
      security:
      - oauth2:
        - inventory_read
      summary: List inventory items
      tags:
      - Inventory
  /inventory/{inventoryId}:
    get:
      operationId: getInventory
      security:
      - oauth2:
        - inventory_read
      summary: Get an inventory item
      tags:
      - Inventory
  /location:
    get:
      operationId: getLocations
      security:
      - oauth2:
        - locations_read
      summary: Get locations
      tags:
      - Locations
  /order:
    get:
      description: All parameters are AND filters
      operationId: getOrders
      security:
      - oauth2:
        - orders_read
      summary: Get Orders
      tags:
      - Orders
    post:
      operationId: createOrder
      security:
      - oauth2:
        - orders_write
      summary: Create Order
      tags:
      - Orders
  /order/estimate:
    post:
      description: This endpoint will provide, where possible, an estimate of pricing
        and fulfillment center assignment of a potential standard (direct to consumer)
        order. \r\nKeep in mind that there are ways for the merchant to change FC
        assignment or product configuration after order creation that could invalidate
        this estimate. \r\nEstimates cannot be returned for items that are unknown,
        out of stock, or too large for fulfillment using standard box sizes. \r\nAdditional
        services such as high-pick fees, shipping insurance, auto-splitting or auto-adding
        items to orders, and signature required are not included in this estimate.
      operationId: createOrderEstimate
      security:
      - oauth2:
        - orders_read
      summary: Estimate Fulfillment Cost For Order
      tags:
      - Orders
  /order/{orderId}:
    get:
      operationId: getOrder
      security:
      - oauth2:
        - orders_read
      summary: Get Order
      tags:
      - Orders
  /order/{orderId}/cancel:
    post:
      operationId: cancelOrder
      security:
      - oauth2:
        - orders_write
      summary: Cancel single Order by Order ID
      tags:
      - Orders
  /order/{orderId}/shipment:
    get:
      operationId: getOrderShipments
      security:
      - oauth2:
        - fulfillments_read
      summary: Get all Shipments for Order
      tags:
      - Orders
  /order/{orderId}/shipment/{shipmentId}:
    get:
      operationId: getOrderShipment
      security:
      - oauth2:
        - fulfillments_read
      summary: Get one Shipment by Order Id and Shipment Id
      tags:
      - Orders
  /order/{orderId}/shipment/{shipmentId}/cancel:
    post:
      operationId: cancelOrderShipment
      security:
      - oauth2:
        - fulfillments_cancel
      summary: Cancel one Shipment by Order Id and Shipment Id
      tags:
      - Orders
  /order/{orderId}/shipment/{shipmentId}/logs:
    get:
      operationId: getOrderShipmentLogs
      security:
      - oauth2:
        - fulfillments_read
      summary: Get logs for one Shipment by Order Id and Shipment Id
      tags:
      - Orders
  /order/{orderId}/shipment/{shipmentId}/timeline:
    get:
      operationId: getOrderShipmentTimeline
      security:
      - oauth2:
        - fulfillments_read
      summary: Get one Shipment's status timeline by Order Id and Shipment Id
      tags:
      - Orders
  /product:
    get:
      operationId: getProducts
      security:
      - oauth2:
        - ProductsRead
      summary: Get multiple products
      tags:
      - Products
    post:
      operationId: createProduct
      security:
      - oauth2:
        - ProductsWrite
      summary: Add a single product to the store
      tags:
      - Products
  /product/batch:
    post:
      operationId: createProductBatch
      security:
      - oauth2:
        - ProductsWrite
      summary: Add multiple products to the store
      tags:
      - Products
  /product/{productId}:
    get:
      operationId: getProduct
      security:
      - oauth2:
        - ProductsRead
      summary: Get a single product
      tags:
      - Products
    put:
      operationId: updateProduct
      security:
      - oauth2:
        - ProductsWrite
      summary: Modify a single product
      tags:
      - Products
  /product/{productId}/inventory:
    get:
      operationId: getProductInventory
      security:
      - oauth2:
        - inventory_read
      summary: Get a list of inventory items by product id
      tags:
      - Inventory
  /receiving:
    post:
      operationId: createReceivingOrder
      security:
      - oauth2:
        - receiving_write
      summary: Create Warehouse Receiving Order
      tags:
      - Receiving
  /receiving/{id}:
    get:
      operationId: getReceivingOrder
      security:
      - oauth2:
        - receiving_read
      summary: Get Warehouse Receiving Order
      tags:
      - Receiving
  /receiving/{id}/cancel:
    post:
      operationId: cancelReceivingOrder
      security:
      - oauth2:
        - receiving_write
      summary: Cancel Warehouse Receiving Order
      tags:
      - Receiving
  /receiving/{id}/labels:
    get:
      operationId: getReceivingOrderLabels
      security:
      - oauth2:
        - receiving_read
      summary: Get Warehouse Receiving Order Box Labels
      tags:
      - Receiving
  /return:
    get:
      operationId: getReturns
      security:
      - oauth2:
        - returns_read
      summary: Get Return Orders
      tags:
      - Returns
    post:
      operationId: createReturn
      security:
      - oauth2:
        - returns_write
      summary: Create Return Order
      tags:
      - Returns
  /return/{id}:
    get:
      operationId: getReturn
      security:
      - oauth2:
        - returns_read
      summary: Get Return Order
      tags:
      - Returns
    put:
      operationId: updateReturn
      security:
      - oauth2:
        - returns_write
      summary: Modify Return Order
      tags:
      - Returns
  /return/{id}/cancel:
    post:
      operationId: cancelReturn
      security:
      - oauth2:
        - returns_write
      summary: Cancel Return Order
      tags:
      - Returns
  /return/{id}/statushistory:
    get:
      operationId: getReturnStatusHistory
      security:
      - oauth2:
        - returns_read
      summary: Get One Return's status history
      tags:
      - Returns
  /shipment/cancelbulk:
    post:
      operationId: cancelShipmentBulk
      security:
      - oauth2:
        - fulfillments_write
      summary: Cancel multiple Shipments by Shipment Id
      tags:
      - Orders
  /shipment/{shipmentId}:
    get:
      operationId: getShipment
      security:
      - oauth2:
        - fulfillments_read
      summary: Get one Shipment by Shipment Id
      tags:
      - Orders
  /shipment/{shipmentId}/cancel:
    post:
      operationId: cancelShipment
      security:
      - oauth2:
        - fulfillments_cancel
      summary: Cancel one Shipment by Shipment Id
      tags:
      - Orders
  /shipment/{shipmentId}/logs:
    get:
      operationId: getShipmentLogs
      security:
      - oauth2:
        - fulfillments_read
      summary: Get logs for one Shipment by Shipment Id
      tags:
      - Orders
  /shipment/{shipmentId}/timeline:
    get:
      operationId: getShipmentTimeline
      security:
      - oauth2:
        - fulfillments_read
      summary: Get one Shipment's status timeline by Shipment Id
      tags:
      - Orders
  /shippingmethod:
    get:
      description: Get all merchants shipping methods
      operationId: getShippingMethodCollection
      security:
      - oauth2:
        - orders_read
      summary: Get shipping methods
      tags:
      - Orders
  /webhook:
    get:
      description: All parameters are AND filters
      operationId: getWebhooks
      security:
      - oauth2: []
      summary: Get Webhooks
      tags:
      - Webhooks
    post:
      operationId: createWebhook
      security:
      - oauth2: []
      summary: Create a new webhook subscription
      tags:
      - Webhooks
  /webhook/{id}:
    delete:
      operationId: deleteWebhook
      security:
      - oauth2: []
      summary: Delete an existing webhook subscription
      tags:
      - Webhooks
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://auth.shipbob.com/connect/integrate
          scopes:
            channels_read: Read channel metadata
            inventory_read: Access read operations
            inventory_write: Access write operations
            locations_read: Access locations read operations
            orders_read: Access read operations
            orders_write: Access write operations
            products_read: Access read operations
            products_write: Access write operations
            receiving_read: Access receiving read operations
            receiving_write: Access receiving write operations
            returns_read: Access returns read operations
            returns_write: Access returns write operations
            webhooks_read: Access read operations
            webhooks_write: Access write operations
          tokenUrl: https://auth.shipbob.com/connect/token
      type: oauth2
